name: master_test

on:
  push:
    branches: [ master ]

jobs:
  master_test:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2      
      - name: Install ffmpeg
        run: brew install ffmpeg
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: NPM install
        run: npm install && npm install -g node-gyp && npm install -g node-addon-api
      - name: Build addon
        run: cd src/native && node-gyp configure && node-gyp build
